
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TuPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      
  service1:
    image: transactionmanagement
    build:
      context: ./transactionManagement
      dockerfile: Dockerfile
    ports:
      - 5100:80

  service2:
    image: productmanagement
    build:
      context: ./productManagement
      dockerfile: Dockerfile
    ports:
      - 5200:80
    volumes:
    - ./productManagement/wwwroot/images:/app/wwwroot/images
volumes:
  sql_data:
